# Github workflow for Continuous Integration

name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Setup browser testing
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Start browser testing tunnel
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start

      - name: Run tests with code coverage
        run: npm run test

      - name: Send code coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop browser testing tunnel
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: stop
